name: Build and deploy ASP.NET Core app to Azure Web App - OrderingAppTeams

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Specific Project
        run: |
          dotnet build YourMainAppProject.csproj --configuration Release
        # Replace 'YourMainAppProject.csproj' with the path to your primary .csproj file.

      - name: Publish Specific Project
        run: |
          dotnet publish YourMainAppProject.csproj -c Release -o ${{ runner.temp }}/myapp
        # Replace 'YourMainAppProject.csproj' with the path to your primary .csproj file.

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OrderingAppTeams'
          slot-name: 'Production'
          package: ${{ runner.temp }}/myapp  # Path to the published app directory
